version: '2'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    container_name: redis-master
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    volumes:
      - './redis-persistence:/bitnami2'

  redis-replica:
    image: 'bitnami/redis:latest'
    container_name: redis-replica
    ports:
      - '6380:6380'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password
      - REDIS_PASSWORD=password

  worker:
    network_mode: 'host'
    depends_on:
      - redis-master
    build: .
